import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <Image
          src="/logo.svg"
          alt="Pagbank Logo"
          width={200}
          height={200}
          priority
        />
      </nav>
      <main className={styles.main}></main>
    </>
  );
}
